### ISSUE TITLE
required positional argument: 'authorization'

### ISSUE THREAD

**Issue by rafpaf** [terror/chatgpt.nvim#10]
I'm getting this error. 

```
error caught in notification handler '/Users/raf/dotfiles/vim/plugged/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py:command:ChatGPT [['testing']]'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pynvim/plugin/host.py", line 140, in _on_notification
    handler(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pynvim/plugin/host.py", line 86, in _wrap_delayed_function

    plugin = cls(self._configure_nvim_for(cls))
  File "/Users/raf/dotfiles/vim/plugged/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py", line 285, in __init__
    self.bot = Bot(Chatbot(Config.load().as_dict()))
  File "/Users/raf/dotfiles/vim/plugged/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py", line 42, in load
    return Config(**json.load(file))
TypeError: Config.__init__() missing 1 required positional argument: 'authorization'
```

Is the `authorization` field in `.chatgpt-nvim.json` needed? I don't think I can access an API key.

**Comment by terror** [comment]
Yeah it's required for now, but you can keep it blank. I'll make it optional soon since not many people may have api keys.

**Comment by rafpaf** [comment]
Thanks. And thanks for creating this plugin. Really stoked to check it out. I've set authorization to an empty string, but then I get this when I try `:ChatGPT query`:

![image](https://user-images.githubusercontent.com/130925/206617561-40ecae1a-c6dd-42fa-b92d-bf1e5907549d.png)

**Comment by terror** [comment]
> Thanks. And thanks for creating this plugin. Really stoked to check it out. I've set authorization to an empty string, but then I get this when I try `:ChatGPT query`:
> 
> ![image](https://user-images.githubusercontent.com/130925/206617561-40ecae1a-c6dd-42fa-b92d-bf1e5907549d.png)

Did you set your `session_token`? Its currently needed to make requests to ChatGPT.

**Comment by rafpaf** [comment]
Yes. I copied a 2481-character string from DevTools > Application > Cookies.

![image](https://user-images.githubusercontent.com/130925/206622017-04b5e1ec-d7d9-4c1a-9098-91a50c218f1c.png)

![image](https://user-images.githubusercontent.com/130925/206621963-4feb133b-fa7e-414a-83e9-0466dc015c59.png)

I'm still getting the same error, though.

**Comment by rafpaf** [comment]
Incidentally, I can get [this repo](https://github.com/acheong08/ChatGPT) working using the access token I can see at https://chat.openai.com/api/auth/session. Is there a way of using this access token with chatgpt.nvim?

**Comment by terror** [comment]
> Incidentally, I can get [this repo](https://github.com/acheong08/ChatGPT) working using the access token I can see at https://chat.openai.com/api/auth/session. Is there a way of using this access token with chatgpt.nvim?

Try updating the dependency `pip3 install revChatGPT --upgrade`, seems to be working for me
