### ISSUE TITLE
E492: Not an editor command: ChatGPT

### ISSUE THREAD

**Issue by vprokopev** [terror/chatgpt.nvim#8]
I installed it with packer, same is in README file here. Got a prompt that it is installed successfully. But when I try to use it I get 'E492: Not an editor command: ChatGPT'.

**Comment by yingzhu146** [comment]
Thanks a lot for the amazing plugins @terror!

I have the same issue

I did `:UpdateRemotePlugins`, it created the rplugin file correctly

`.local/share/nvim/rplugin.vim`

containing

```
call remote#host#RegisterPlugin('python3', '/Users/lucanaef/.local/share/nvim/site/pack/packer/opt/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py', [
      \ {'sync': v:false, 'name': 'ChatGPT', 'type': 'command', 'opts': {'nargs': '1'}},
     \ ])
```

I tried to manually source this file too, but get hit with a 

```
E605: Exception not caught: Plugin "/Users/yingzhu/.local/share/nvim/site/pack/packer/opt/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py" is already registered
```

So clearly it's loaded.

Nonetheless, get the 492.

maybe Important to note: I'm lazy loading on `ChatGPT` command via packer, but even if I manually force load it and do the above dance it doesn't work.

Thanks a lot for the help!

**Comment by yingzhu146** [comment]
Thanks a lot for the amazing plugins @terror!

I have the same issue

I did `:UpdateRemotePlugins`, it created the rplugin file correctly

`.local/share/nvim/rplugin.vim`

containing

```
call remote#host#RegisterPlugin('python3', '/Users/yingzhu/.local/share/nvim/site/pack/packer/opt/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py', [
      \ {'sync': v:false, 'name': 'ChatGPT', 'type': 'command', 'opts': {'nargs': '1'}},
     \ ])
```

I tried to manually source this file too, but get hit with a 

```
E605: Exception not caught: Plugin "/Users/yingzhu/.local/share/nvim/site/pack/packer/opt/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py" is already registered
```

So clearly it's loaded.

Nonetheless, get the 492.

maybe Important to note: I'm lazy loading on `ChatGPT` command via packer, but even if I manually force load it and do the above dance it doesn't work.

Thanks a lot for the help!

**Comment by kiil** [comment]
I have the same issue. The plugin is loaded, but the `ChatGPT` command just returns:

`E492: Ikke en editor-kommando: ChatGPT` which translates to 'E492: Not an editor command: ChatGPT'.

**Comment by TheJoeSchr** [comment]
On arch linux this worked, plugin was installed via `Plug`.

I created this file: ~/.local/share/nvim/rplugin.vim

```
call remote#host#RegisterPlugin('python3', '$HOME/.vim/plugged/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py', [
      \ {'sync': v:false, 'name': 'ChatGPT', 'type': 'command', 'opts': {'nargs': '1'}},
     \ ])
```
observe the different path to `.vim/plugged` in comparion with @yingzhu146 post.

now `:ChatGPT` is active and autocompletes

**Comment by TheJoeSchr** [comment]
now I get this error
```
Encountered ImportError loading plugin at $HOME/.vim/plugged/chatgpt.nvim/rplugin/python3/chatgpt_nvim.py: No mo
dule named 'chatgpt_nvim'
Traceback (most recent call last):
  File "/home/joe/.py3nvim/lib/python3.10/site-packages/pynvim/plugin/host.py", line 164, in _load
    file, pathname, descr = find_module(name, [directory])
  File "/home/joe/.py3nvim/lib/python3.10/site-packages/pynvim/compat.py", line 30, in find_module
    return original_find_module(fullname, path)
  File "/usr/lib/python3.10/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'chatgpt_nvim'
```

**Comment by TheJoeSchr** [comment]
So now I found out my python host path via
`:let g:python3_host_prog` => $PY_PATH
 and then called it and installed the requirements again 
`$PY_PATH -m pip install -r ~/.vim/plugged/chatgpt.nvim/requirements.txt`

now I can use `:ChatGPT write me something` without any `ModuleNotFoundError`

but I got an error about Notification not registered for ChatGPT plugin. I could "solve" this by actually opening an existing file :D

**Comment by pannet1** [comment]
i have tried all steps mentioned by @TheJoeSchr  but i still get the notification error

`no notification handler registered for "/home/pannet1/.loc
al/share/nvim/site/pack/packer/start/chatgpt.nvim/rplugin/
python3/chatgpt_nvim.py:command:ChatGPT"  `

i am on EOS a derivative of Arch LInux
